provider:
  environment:
    CHANGE_VALUE: "foo"
    MONGODB_URI: "mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]"

custom:
  customDomain:
    domainName: "dev.change.com"
    certificateName: "*.change.com"
    enabled: true
    basePathMappings:
      - path: /
        stage: dev