service: "demo"

plugins:
 - "@kalarrs/serverless-project-utils"
 - "@kalarrs/serverless-shared-api-gateway"

provider:
  name: aws
  runtime: dotnetcore2.1
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  apiGatewayRestApiName: ${file(../serverless.yml):provider.apiGatewayRestApiName}
  
  environment:
#    FOO: ${env:FOO, file(../serverless.yml):provider.environment.FOO}

package:
  artifact: src/bin/release/netcoreapp2.1/deploy-package.zip

functions:
#  get:
#    handler: CsharpHandlers::changes.Handler::Get
#    events:
#      - http:
#          method: get
#          path: path
#          cors: true

custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5010
