service: "change-name"

plugins:
 - "@kalarrs/serverless-project-utils"
 - "@kalarrs/serverless-shared-api-gateway"

provider:
  name: aws
  runtime: dotnetcore2.0
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  apiGatewayRestApiName: ${file(../serverless.yml):provider.apiGatewayRestApiName}
  
  environment:
    CHANGE_VALUE: ${env:CHANGE_VALUE, file(../serverless.yml):provider.environment.CHANGE_VALUE}

package:
  artifact: src/bin/release/netcoreapp2.0/deploy-package.zip

functions:
  # list
  getChanges:
    handler: CsharpHandlers::changes.Handler::GetChanges
    events:
      - http:
          method: get
          path: changes
          cors: true

  # create
  postChanges:
    handler: CsharpHandlers::changes.Handler::PostChanges
    events:
      - http:
          method: post
          path: changes
          cors: true

  # put
  putChanges:
    handler: CsharpHandlers::changes.Handler::PutChange
    events:
      - http:
          method: put
          path: changes/{changeId}
          cors: true

  # delete
  deleteChanges:
    handler: CsharpHandlers::changes.Handler::DeleteChange
    events:
      - http:
          method: delete
          path: changes/{changeId}
          cors: true

custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5005
